version: "3"

services:
  api:
    container_name: bdmis_api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: production #development
    # command: npm run dev
    environment:
      - DOCKER=TRUE
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"

  # Mail app
  mail:
    container_name: bdmis_mail
    build:
      context: .
      dockerfile: ./apps/mail/Dockerfile
      target: production #development
    # command: npm run dev mail
    env_file:
      - .env
    depends_on:
      - api
      - postgres

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # postgresql
  postgres:
    image: "postgres:14"
    container_name: bdmis_postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
